#!/bin/sh

rbenv install 2.4.2
rbenv global 2.4.2

if [ -d ~/.janus ]; then
  rake -f ~/.vim/Rakefile
else
  curl -L https://bit.ly/janus-bootstrap | bash
fi

if [ -d ~/.oh-my-zsh ]; then
  sh "$ZSH/tools/upgrade.sh"
else
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi


