#!/bin/sh

rbenv versions | grep 2.6.0
if [[ $? != 0 ]] ; then
  rbenv install 2.6.0
fi
rbenv global 2.6.0

if [ -d ~/.janus ]; then
  rake -f ~/.vim/Rakefile
else
  curl -L https://bit.ly/janus-bootstrap | bash
fi

if [ -d ~/.oh-my-zsh ]; then
  sh "$ZSH/tools/upgrade.sh"
else
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi
